# local unix socket connections (needed for init scripts)
local   all             all                                     trust

# allow app connections inside docker network
host    all             all             127.0.0.1/32            md5
host    all             all             ::1/128                 md5
host    all             all             0.0.0.0/0               md5

# replication
host    replication     replicator      0.0.0.0/0               md5
